learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views
#for templates tag
app_name='basic_app'

urlpatterns=[
url(r'^relative/$',views.relative,name='relative'),
url(r'^other/$',views.other,name='other')
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^basic_app/',include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    dec={'text':'hi there this is text','number':100}
    return render(request,'basic_app/index.html',dec)
def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="{% static "css/bootstrap.css" %}"/>

        <title></title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="navbar-nav">
    <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
    <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
    <a class="nav-item nav-link" href="{% url 'basic_app:other' %}">Other</a>
  </div>
</nav>


        <div class="container">
            {% block body_block%}
            {% endblock %}
        </div>

    </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
{% block body_block%}
<h1>welcome to index</h1>
<h2>this is index</h2>
<h1>{{text|cut:' the '}}</h1>
<h1>{{number|add:"99"}}</h1>
{% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{%block body_block%}
<h1>welcome to other</h1>
<h2>this is an example of tamplets inherit</h2>
{% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
<h1>welcome to relative url templates</h1>
<a href="{% url 'basic_app:relative' %}"> relative page</a>
<a href="{%url 'basic_app:other' %}">other</a>
<a href="{% url 'admin:index' %}">admin</a>

    </body>
</html>